// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://onzzazxyfjdgvxhoxstr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9uenphenh5ZmpkZ3Z4aG94c3RyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMTQ1NzcsImV4cCI6MjA2MzU5MDU3N30.-ThGxqFq0wwD6cQEhZtYYBQ6hCVPWyMUNnTXEvc-JRw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);